### ISSUE TITLE
Running on Mac

### ISSUE THREAD

**Issue by edwardqiu** [jrjparks/myManga#28]
Hi,

I'm currently running on Mac OSX 10.11 with Wineskin 2.6.2 and WSWine1.9.2 installed. myManga seems not run, because of dependency issues.

Would you mind telling me what frameworks I need to install or if I need to download and import the dlls?

Thanks for your time

**Comment by jrjparks** [comment]
Hi @edwardqiu,
myManga is built for .NET v4.6.1 and uses HtmlAgilityPack v1.4.9 and log4net v2.0.5.
Since I do not own a Mac and have developed this for a windows only environment the app uses WPF. If you would like to run myManga on a Mac without dual booting to windows or using a second PC I would recommend [Parallels](https://www.parallels.com/products/desktop/) over Wine.

**Comment by jrjparks** [comment]
Closing this issue as the question was answered 10 days ago and no new comments have been made.
