### ISSUE TITLE
Unable to retrieve chapters for Onepunch-Man

### ISSUE THREAD

**Issue by scotty531** [jrjparks/myManga#40]
The chapters are not available and loads of errors that look like this are in mymanga.log.2:
WARN - Unable to parse from MangaPanda-English for Onepunch-Man.
System.FormatException: String was not recognized as a valid DateTime.

I also get "There was an error decoding Batoto/MangaTraders (). Please reauthenticate." when launching the application even though my login details are correct (I've tried both email and username).

http://pastebin.com/pUivUMu4

**Comment by jrjparks** [comment]
Some things to check would be:
1. Are you connected to the internet when you start myManga? For the application to re-authenticate it will attempt to login. That error is shown when this fails.
2. The warnings now showing in the logs may have always happened, check with your web browser to see if the page is loading correctly. I just tested loading Onepunch-man from both MangaPanda and MangaReader with it loading correctly.

**Comment by scotty531** [comment]
I fixed the authntication error by deleting mymanga.auth.conf. Yes I'm connected to the internet and it loads in my browser.

**Comment by jrjparks** [comment]
What happens if you re-search and re-add Onepunch-man?

**Comment by scotty531** [comment]
No change.

**Comment by jrjparks** [comment]
This is very odd. I think it may have to do with you and how I have C# handle the DateTime parse. My guess is that your systems CultureInfo is not the same as mine and that's on me. I'll try to get a fix out for this soon.
On the note of deleting the ```mymanga.auth.conf```, all you should need to do would be to go the the settings and re-login. This happens due to how your password is hashed and when myManga is updated you need to rehash.

**Comment by jrjparks** [comment]
See if the Plugins-Fix#40 fixes your error.
https://github.com/jrjparks/myManga/releases/tag/3.0.5933.24612

**Comment by scotty531** [comment]
It works now, thanks!
